name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 176.98.8.185
        username: sonja
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        script: |
          cd ~/devops_project_intel
          git pull origin main
